a = input('Digite algo: ')
print('Qual o tipo?  |',type(a))
print('É numeral?    |', a.isalnum())
print('É alfabético? |', a.isalpha())
print('É dígito?     |', a.isdigit())
print('É minúsculo?  |', a.islower())
print('É imprimível? |', a.isprintable())