op = int(input('Digite um número, para ver sua tabuada. '))
a = op+1
b = op+2
c = op+3
d = op+4
e = op+5
f = op+6
g = op+7
h = op+8
i = op+9
j = op+10
print(f'{op} + 1   = {a}')
print(f'{op} + 2   = {b}')
print(f'{op} + 3   = {c}')
print(f'{op} + 4   = {d}')
print(f'{op} + 5   = {e}')
print(f'{op} + 6   = {f}')
print(f'{op} + 7   = {g}')
print(f'{op} + 8   = {h}')
print(f'{op} + 9   = {i}')
print(f'{op} + 10  = {j}')